package apps

import "github.com/sysdiglabs/promcat/pkg/app"

// AwsFargate Creates a AWS Fargate app for testing.
// Should be equals to the one generated by /tests/fixtures/apps/aws-fargate.yaml
func AwsFargate() *app.App {
	return &app.App{
		ID:                "aws-fargate",
		Kind:              "App",
		Name:              "AWS Fargate",
		Keywords:          []string{"aws", "serverless", "containers"},
		AvailableVersions: []string{"1.0.0", "1.0.1"},
		Description:       "# AWS Fargate\n",
		ShortDescription:  "AWS serverless containers",
		Icon:              "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/500px-Amazon_Web_Services_Logo.svg.png",
		Website:           "https://aws.amazon.com/fargate/",
		Available:         true,
	}
}

// AwsLambda Creates a AWS LAmbda app for testing.
// Should be equals to the one generated by /tests/fixtures/apps/aws-lambda.yaml
func AwsLambda() *app.App {
	return &app.App{
		ID:                "aws-lambda",
		Kind:              "App",
		Name:              "AWS Lambda",
		Keywords:          []string{"aws", "serverless", "containers"},
		AvailableVersions: []string{"1.0.0", "1.0.1"},
		Description:       "# AWS Lambda\n",
		ShortDescription:  "AWS serverless functions",
		Icon:              "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/500px-Amazon_Web_Services_Logo.svg.png",
		Website:           "https://aws.amazon.com/lambda/",
		Available:         true,
	}
}
